name: LaTeX Build

on:
  push:
    branches:
      - main  # main 브랜치에 커밋될 때마다 빌드
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up LaTeX environment
      run: sudo apt-get update && sudo apt-get install -y texlive-full

    - name: Compile LaTeX document
      run: main.tex  # 'yourfile.tex'을 실제 LaTeX 파일 이름으로 변경하세요.

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: document
        path: yourfile.pdf  # PDF 파일 이름을 지정합니다.
